kind: pipeline
name: default

trigger:
  branch:
    - drone
    
steps:
- name: build
  image: plugins/hugo:latest
  settings:
    hugo_version: 0.62.0
    validate: true
- name: push
  image: appleboy/drone-git-push
  environment:
      SSH_KEY:
        from_secret: ssh_key
  settings:
    branch: master
    remote: git@github.com:Dimitrius93/LoveIt.git
    force: false
    commit: true
    commands:
      - echo "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 $HOME/.ssh/known_hosts
