kind: pipeline
name: default

trigger:
  branch:
    - drone
    
steps:
- name: build
  image: plugins/hugo:latest
  settings:
    hugo_version: 0.62.0
    validate: true

steps:
- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: github.com/Dimitrius93/LoveIt
    force: false
    commit: true
