kind: pipeline
name: default

trigger:
  branch:
    - drone
    
steps:
- name: build
  image: plugins/hugo:latest
  settings:
    hugo_version: 0.62.0
    validate: true

steps:
- name: git-push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:Dimitrius93/LoveIt.git
    ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPyJ/U9ZvJWoY+5j71JDBx8IYfBrivduuaUDLd0yJUA0 egik993@gmail.com
    force: false
    commit: true
