kind: pipeline
name: default

trigger:
  branch:
    - drone
    
steps:
- name: build
  image: plugins/hugo:latest
  settings:
    hugo_version: 0.62.0
    validate: true
- name: push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:Dimitrius93/LoveIt.git
    force: false
    commit: true
    ssh_key:
      from_secret: ssh_key
